[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_FORMS_DEBUG = "true"

# 表单处理配置
[build.processing]
  skip_processing = false

# 表单设置
[[forms]]
  name = "user-study-results"
  action = "/"
  method = "POST"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 重定向规则
[[redirects]]
  from = "/groupA"
  to = "/groupA.html"
  status = 200

[[redirects]]
  from = "/groupB"
  to = "/groupB.html"
  status = 200
